name: 'Glo Add Comment To Card'
description: 'GitHub Action to add a comment to a card'
branding:
  color: 'blue'
  icon: 'message-circle'
inputs:
  authToken:
    description: Auth token for user
    required: true
  boardID:
    description: ID of board
    required: true
  cardID:
    description: ID of card
    required: true
  comment:
    description: Comment to add to the card
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
