name: 'Glo Boards Add Comment To Cards'
description: 'GitHub action to add a comment to Glo Boards cards'
branding:
  color: 'blue'
  icon: 'message-circle'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  comment:
    description: Comment to add to the card
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
